// DISCOVER — mock listing data
// 20 Hyderabad properties. Coordinates are approximate locality centroids,
// jittered per listing — accurate enough to sit correctly on a Leaflet map,
// not survey-grade. Prices reflect mid-2026 Hyderabad market bands.

export type PropertyType =
  | "Apartment"
  | "Villa"
  | "Independent House"
  | "Builder Floor"
  | "Penthouse"
  | "Plot";

export type ListingStatus = "For Sale" | "New Launch" | "Under Construction" | "Ready to Move";

export type Furnishing = "Unfurnished" | "Semi-furnished" | "Fully furnished";

export interface Agent {
  name: string;
  phone: string;
  email: string;
  agency: string;
  avatar: string;
}

export interface Listing {
  id: string;
  title: string;
  address: string;
  locality: string;
  city: string;
  pincode: string;
  lat: number;
  lng: number;
  price: number;          // in rupees
  pricePerSqft: number;
  beds: number;
  baths: number;
  sqft: number;
  propertyType: PropertyType;
  status: ListingStatus;
  furnishing: Furnishing;
  facing: string;
  floor: number | null;
  totalFloors: number | null;
  yearBuilt: number;
  parking: number;
  description: string;
  amenities: string[];
  images: string[];
  agent: Agent;
  listedDate: string;     // ISO
  featured: boolean;
}

const agents: Record<string, Agent> = {
  rajesh: {
    name: "Rajesh Varma",
    phone: "+91 98490 21134",
    email: "rajesh@discover.in",
    agency: "Discover Premium",
    avatar: "/images/agents/rajesh.jpg",
  },
  sneha: {
    name: "Sneha Reddy",
    phone: "+91 99590 44821",
    email: "sneha@discover.in",
    agency: "Discover Premium",
    avatar: "/images/agents/sneha.jpg",
  },
  imran: {
    name: "Imran Qureshi",
    phone: "+91 90005 77310",
    email: "imran@discover.in",
    agency: "Discover Residential",
    avatar: "/images/agents/imran.jpg",
  },
  divya: {
    name: "Divya Prasad",
    phone: "+91 91777 30256",
    email: "divya@discover.in",
    agency: "Discover Residential",
    avatar: "/images/agents/divya.jpg",
  },
};

export const listings: Listing[] = [
  {
    id: "rt-001",
    title: "Contemporary 4BHK villa with private lawn",
    address: "Road No. 45, Jubilee Hills",
    locality: "Jubilee Hills",
    city: "Hyderabad",
    pincode: "500033",
    lat: 17.4326,
    lng: 78.4071,
    price: 145000000,
    pricePerSqft: 16800,
    beds: 4,
    baths: 5,
    sqft: 8630,
    propertyType: "Villa",
    status: "Ready to Move",
    furnishing: "Fully furnished",
    facing: "East",
    floor: null,
    totalFloors: 2,
    yearBuilt: 2021,
    parking: 4,
    description:
      "A double-height living room opens onto a west-facing lawn shaded by mature rain trees. Italian marble through the ground floor, imported modular kitchen, and a separate guest annexe with its own entrance. Located on one of Jubilee Hills' quieter internal roads, four minutes from Apollo Hospital.",
    amenities: ["Private lawn", "Home theatre", "Servant quarters", "Solar water heating", "Borewell", "CCTV", "Power backup"],
    images: ["/images/listings/rt-001-1.jpg", "/images/listings/rt-001-2.jpg", "/images/listings/rt-001-3.jpg"],
    agent: agents.rajesh,
    listedDate: "2026-06-02",
    featured: true,
  },
  {
    id: "rt-002",
    title: "3BHK in gated high-rise, Financial District views",
    address: "Aparna Sarovar Zenith, Nallagandla",
    locality: "Nallagandla",
    city: "Hyderabad",
    pincode: "500019",
    lat: 17.4823,
    lng: 78.3115,
    price: 21500000,
    pricePerSqft: 8100,
    beds: 3,
    baths: 3,
    sqft: 2655,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Semi-furnished",
    facing: "North-East",
    floor: 14,
    totalFloors: 22,
    yearBuilt: 2020,
    parking: 2,
    description:
      "Corner unit on the 14th floor with an unobstructed line of sight toward the Financial District skyline. Wraparound balcony off the living and master bedroom. The society has a 40,000 sqft clubhouse and is a seven-minute drive to Wipro Circle.",
    amenities: ["Clubhouse", "Swimming pool", "Gym", "Children's play area", "Power backup", "Lift", "Gated community", "Visitor parking"],
    images: ["/images/listings/rt-002-1.jpg", "/images/listings/rt-002-2.jpg", "/images/listings/rt-002-3.jpg"],
    agent: agents.sneha,
    listedDate: "2026-06-19",
    featured: true,
  },
  {
    id: "rt-003",
    title: "Spacious 2BHK near Kukatpally metro",
    address: "KPHB Phase 6, Kukatpally",
    locality: "Kukatpally",
    city: "Hyderabad",
    pincode: "500072",
    lat: 17.4948,
    lng: 78.3996,
    price: 8200000,
    pricePerSqft: 6050,
    beds: 2,
    baths: 2,
    sqft: 1355,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Unfurnished",
    facing: "East",
    floor: 5,
    totalFloors: 9,
    yearBuilt: 2016,
    parking: 1,
    description:
      "Practical east-facing two-bedroom in an established KPHB block, 600 metres from the Kukatpally metro station. Vitrified flooring, covered parking, and a resident association that maintains the building well. Forum Sujana Mall is a ten-minute walk.",
    amenities: ["Lift", "Power backup", "Covered parking", "Security", "Borewell", "Metro nearby"],
    images: ["/images/listings/rt-003-1.jpg", "/images/listings/rt-003-2.jpg"],
    agent: agents.imran,
    listedDate: "2026-07-01",
    featured: false,
  },
  {
    id: "rt-004",
    title: "Sky villa with terrace garden in Kokapet",
    address: "My Home Apas, Kokapet",
    locality: "Kokapet",
    city: "Hyderabad",
    pincode: "500075",
    lat: 17.4055,
    lng: 78.3271,
    price: 68000000,
    pricePerSqft: 11400,
    beds: 4,
    baths: 5,
    sqft: 5965,
    propertyType: "Penthouse",
    status: "Ready to Move",
    furnishing: "Fully furnished",
    facing: "West",
    floor: 31,
    totalFloors: 32,
    yearBuilt: 2023,
    parking: 3,
    description:
      "Duplex penthouse across the top two floors, with a 1,200 sqft private terrace and plunge pool. Floor-to-ceiling glazing on the western face catches the evening light over the Osman Sagar catchment. Private lift lobby.",
    amenities: ["Private terrace", "Plunge pool", "Private lift", "Concierge", "Gym", "Clubhouse", "Power backup", "EV charging"],
    images: ["/images/listings/rt-004-1.jpg", "/images/listings/rt-004-2.jpg", "/images/listings/rt-004-3.jpg", "/images/listings/rt-004-4.jpg"],
    agent: agents.rajesh,
    listedDate: "2026-05-14",
    featured: true,
  },
  {
    id: "rt-005",
    title: "3BHK new launch off ORR, Tellapur",
    address: "Tellapur Main Road, Tellapur",
    locality: "Tellapur",
    city: "Hyderabad",
    pincode: "502032",
    lat: 17.4901,
    lng: 78.2823,
    price: 14800000,
    pricePerSqft: 7250,
    beds: 3,
    baths: 3,
    sqft: 2040,
    propertyType: "Apartment",
    status: "New Launch",
    furnishing: "Unfurnished",
    facing: "North",
    floor: 8,
    totalFloors: 26,
    yearBuilt: 2028,
    parking: 2,
    description:
      "Pre-launch pricing on a 26-storey tower with possession expected late 2028. Two minutes from the ORR Exit 3 ramp, which puts the Financial District within a fifteen-minute drive outside peak hours. RERA registered.",
    amenities: ["Clubhouse", "Swimming pool", "Gym", "Jogging track", "Amphitheatre", "Power backup", "Gated community"],
    images: ["/images/listings/rt-005-1.jpg", "/images/listings/rt-005-2.jpg"],
    agent: agents.divya,
    listedDate: "2026-07-08",
    featured: false,
  },
  {
    id: "rt-006",
    title: "Heritage bungalow on 900 sq yd, Banjara Hills",
    address: "Road No. 12, Banjara Hills",
    locality: "Banjara Hills",
    city: "Hyderabad",
    pincode: "500034",
    lat: 17.4126,
    lng: 78.4482,
    price: 195000000,
    pricePerSqft: 14200,
    beds: 5,
    baths: 6,
    sqft: 13730,
    propertyType: "Independent House",
    status: "For Sale",
    furnishing: "Unfurnished",
    facing: "South-East",
    floor: null,
    totalFloors: 2,
    yearBuilt: 1994,
    parking: 6,
    description:
      "A 1990s Deccan bungalow on 900 square yards, retaining its original teak joinery, jaali screens and courtyard. Sold as-is — most buyers at this level will redevelop, but the plot and the road frontage are the point. Rare inventory on Road No. 12.",
    amenities: ["Courtyard", "Servant quarters", "Borewell", "Mature garden", "Compound wall", "Power backup"],
    images: ["/images/listings/rt-006-1.jpg", "/images/listings/rt-006-2.jpg", "/images/listings/rt-006-3.jpg"],
    agent: agents.rajesh,
    listedDate: "2026-04-27",
    featured: true,
  },
  {
    id: "rt-007",
    title: "Compact 2BHK, walk to HITEC City",
    address: "Silicon Valley, Madhapur",
    locality: "Madhapur",
    city: "Hyderabad",
    pincode: "500081",
    lat: 17.4483,
    lng: 78.3915,
    price: 12400000,
    pricePerSqft: 9100,
    beds: 2,
    baths: 2,
    sqft: 1360,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Semi-furnished",
    facing: "East",
    floor: 6,
    totalFloors: 11,
    yearBuilt: 2018,
    parking: 1,
    description:
      "The rare Madhapur unit you can actually walk to work from — eleven minutes on foot to the Cyber Towers junction. Semi-furnished with wardrobes and modular kitchen already fitted. Strong rental demand if you're buying to let.",
    amenities: ["Gym", "Lift", "Power backup", "Covered parking", "Security", "Rainwater harvesting"],
    images: ["/images/listings/rt-007-1.jpg", "/images/listings/rt-007-2.jpg"],
    agent: agents.sneha,
    listedDate: "2026-06-25",
    featured: false,
  },
  {
    id: "rt-008",
    title: "4BHK independent house, Sainikpuri",
    address: "Kakateeya Hills, Sainikpuri",
    locality: "Sainikpuri",
    city: "Hyderabad",
    pincode: "500094",
    lat: 17.4936,
    lng: 78.5482,
    price: 24500000,
    pricePerSqft: 7150,
    beds: 4,
    baths: 4,
    sqft: 3425,
    propertyType: "Independent House",
    status: "Ready to Move",
    furnishing: "Unfurnished",
    facing: "North",
    floor: null,
    totalFloors: 2,
    yearBuilt: 2012,
    parking: 2,
    description:
      "Well-built G+1 on 267 square yards in a quiet defence-colony pocket. Ground floor is currently let out, giving immediate rental income while you occupy the first. Wide 40-foot road, low traffic, established neighbourhood.",
    amenities: ["Independent entrance", "Terrace", "Borewell", "Compound wall", "Power backup", "Parking"],
    images: ["/images/listings/rt-008-1.jpg", "/images/listings/rt-008-2.jpg", "/images/listings/rt-008-3.jpg"],
    agent: agents.imran,
    listedDate: "2026-06-11",
    featured: false,
  },
  {
    id: "rt-009",
    title: "Premium 3BHK in Gachibowli tech corridor",
    address: "Lanco Hills, Manikonda",
    locality: "Manikonda",
    city: "Hyderabad",
    pincode: "500089",
    lat: 17.4045,
    lng: 78.3822,
    price: 18900000,
    pricePerSqft: 8400,
    beds: 3,
    baths: 3,
    sqft: 2250,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Semi-furnished",
    facing: "West",
    floor: 17,
    totalFloors: 24,
    yearBuilt: 2019,
    parking: 2,
    description:
      "Seventeenth-floor unit in a township with its own retail street, school and medical centre — you rarely need to leave the gate. West-facing balcony, good cross-ventilation. Ten minutes to Gachibowli, twenty to the airport via ORR.",
    amenities: ["Township retail", "School inside", "Swimming pool", "Gym", "Clubhouse", "Power backup", "Gated community", "Lift"],
    images: ["/images/listings/rt-009-1.jpg", "/images/listings/rt-009-2.jpg"],
    agent: agents.divya,
    listedDate: "2026-07-03",
    featured: false,
  },
  {
    id: "rt-010",
    title: "Budget 2BHK near Miyapur metro terminus",
    address: "Chanda Nagar Road, Miyapur",
    locality: "Miyapur",
    city: "Hyderabad",
    pincode: "500049",
    lat: 17.4968,
    lng: 78.3578,
    price: 5900000,
    pricePerSqft: 5150,
    beds: 2,
    baths: 2,
    sqft: 1145,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Unfurnished",
    facing: "North-East",
    floor: 3,
    totalFloors: 5,
    yearBuilt: 2014,
    parking: 1,
    description:
      "Straightforward entry-level buy a kilometre from the Miyapur metro terminus, which makes the whole Red Line commute viable without a car. Building is a decade old but structurally sound with a functioning association.",
    amenities: ["Lift", "Power backup", "Parking", "Security", "Metro nearby", "Borewell"],
    images: ["/images/listings/rt-010-1.jpg", "/images/listings/rt-010-2.jpg"],
    agent: agents.imran,
    listedDate: "2026-07-12",
    featured: false,
  },
  {
    id: "rt-011",
    title: "Gated villa community plot, Shankarpally",
    address: "Aurum Estates, Shankarpally Road",
    locality: "Shankarpally",
    city: "Hyderabad",
    pincode: "501203",
    lat: 17.4451,
    lng: 78.1985,
    price: 9600000,
    pricePerSqft: 3200,
    beds: 0,
    baths: 0,
    sqft: 3000,
    propertyType: "Plot",
    status: "For Sale",
    furnishing: "Unfurnished",
    facing: "East",
    floor: null,
    totalFloors: null,
    yearBuilt: 2026,
    parking: 0,
    description:
      "333 square yard east-facing plot in a HMDA-approved gated layout with internal roads, drainage and street lighting already laid. Construction permitted to G+2. The Regional Ring Road alignment passes within four kilometres.",
    amenities: ["HMDA approved", "Gated layout", "Internal roads", "Street lighting", "Drainage", "Compound wall"],
    images: ["/images/listings/rt-011-1.jpg", "/images/listings/rt-011-2.jpg"],
    agent: agents.divya,
    listedDate: "2026-05-30",
    featured: false,
  },
  {
    id: "rt-012",
    title: "Renovated 3BHK builder floor, Begumpet",
    address: "Prakash Nagar, Begumpet",
    locality: "Begumpet",
    city: "Hyderabad",
    pincode: "500016",
    lat: 17.4435,
    lng: 78.4691,
    price: 16200000,
    pricePerSqft: 8650,
    beds: 3,
    baths: 3,
    sqft: 1875,
    propertyType: "Builder Floor",
    status: "Ready to Move",
    furnishing: "Fully furnished",
    facing: "South",
    floor: 2,
    totalFloors: 4,
    yearBuilt: 2009,
    parking: 2,
    description:
      "Fully renovated last year — rewired, replumbed, new kitchen and bathrooms. Only one flat per floor, so no shared walls. Prakash Nagar is central without being loud, and Begumpet metro is a six-minute walk.",
    amenities: ["Single flat per floor", "Modular kitchen", "Lift", "Power backup", "Covered parking", "Metro nearby"],
    images: ["/images/listings/rt-012-1.jpg", "/images/listings/rt-012-2.jpg", "/images/listings/rt-012-3.jpg"],
    agent: agents.sneha,
    listedDate: "2026-06-07",
    featured: false,
  },
  {
    id: "rt-013",
    title: "5BHK villa in gated community, Kompally",
    address: "Alekhya Casa Grande, Kompally",
    locality: "Kompally",
    city: "Hyderabad",
    pincode: "500014",
    lat: 17.5401,
    lng: 78.4869,
    price: 32500000,
    pricePerSqft: 7050,
    beds: 5,
    baths: 5,
    sqft: 4610,
    propertyType: "Villa",
    status: "Ready to Move",
    furnishing: "Semi-furnished",
    facing: "East",
    floor: null,
    totalFloors: 3,
    yearBuilt: 2017,
    parking: 3,
    description:
      "Triple-storey villa in a 90-unit gated enclave with a shared clubhouse and tennis court. Private garden front and rear, home office on the top floor. Kompally has matured considerably since 2017 — several international schools within three kilometres.",
    amenities: ["Private garden", "Clubhouse", "Tennis court", "Swimming pool", "Gated community", "Power backup", "Servant quarters", "Borewell"],
    images: ["/images/listings/rt-013-1.jpg", "/images/listings/rt-013-2.jpg", "/images/listings/rt-013-3.jpg"],
    agent: agents.divya,
    listedDate: "2026-05-21",
    featured: true,
  },
  {
    id: "rt-014",
    title: "2BHK under construction, Bachupally",
    address: "Nizampet Road, Bachupally",
    locality: "Bachupally",
    city: "Hyderabad",
    pincode: "500090",
    lat: 17.5462,
    lng: 78.3877,
    price: 7400000,
    pricePerSqft: 5600,
    beds: 2,
    baths: 2,
    sqft: 1320,
    propertyType: "Apartment",
    status: "Under Construction",
    furnishing: "Unfurnished",
    facing: "North",
    floor: 7,
    totalFloors: 14,
    yearBuilt: 2027,
    parking: 1,
    description:
      "Handover scheduled for March 2027, currently at eighth-slab stage. Construction-linked payment plan available. Bachupally has absorbed a lot of the Kukatpally overflow and pricing here still trails Nizampet by roughly eight percent.",
    amenities: ["Clubhouse", "Gym", "Children's play area", "Power backup", "Lift", "Gated community", "Rainwater harvesting"],
    images: ["/images/listings/rt-014-1.jpg", "/images/listings/rt-014-2.jpg"],
    agent: agents.imran,
    listedDate: "2026-07-05",
    featured: false,
  },
  {
    id: "rt-015",
    title: "Designer 3BHK overlooking Durgam Cheruvu",
    address: "Rajapushpa Summit, Nanakramguda",
    locality: "Nanakramguda",
    city: "Hyderabad",
    pincode: "500032",
    lat: 17.4229,
    lng: 78.3419,
    price: 34000000,
    pricePerSqft: 10600,
    beds: 3,
    baths: 4,
    sqft: 3210,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Fully furnished",
    facing: "North-East",
    floor: 22,
    totalFloors: 30,
    yearBuilt: 2024,
    parking: 2,
    description:
      "Interior-designed unit finished in oak and brushed brass, sold with furniture. The north-east glazing frames Durgam Cheruvu and the cable bridge. Walking distance to the Financial District office cluster.",
    amenities: ["Lake view", "Concierge", "Infinity pool", "Gym", "Business centre", "EV charging", "Power backup", "Private lift lobby"],
    images: ["/images/listings/rt-015-1.jpg", "/images/listings/rt-015-2.jpg", "/images/listings/rt-015-3.jpg", "/images/listings/rt-015-4.jpg"],
    agent: agents.rajesh,
    listedDate: "2026-06-29",
    featured: true,
  },
  {
    id: "rt-016",
    title: "3BHK with study, Narsingi",
    address: "Vasavi Atlantis, Narsingi",
    locality: "Narsingi",
    city: "Hyderabad",
    pincode: "500089",
    lat: 17.3897,
    lng: 78.3541,
    price: 17600000,
    pricePerSqft: 7900,
    beds: 3,
    baths: 3,
    sqft: 2230,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Semi-furnished",
    facing: "East",
    floor: 11,
    totalFloors: 19,
    yearBuilt: 2022,
    parking: 2,
    description:
      "Three bedrooms plus a genuine study — not a converted utility. Narsingi sits right on the ORR with quick access both to the Financial District and toward Shamshabad airport. Good school cluster within two kilometres.",
    amenities: ["Study room", "Swimming pool", "Gym", "Clubhouse", "Gated community", "Power backup", "Lift", "Visitor parking"],
    images: ["/images/listings/rt-016-1.jpg", "/images/listings/rt-016-2.jpg"],
    agent: agents.sneha,
    listedDate: "2026-06-16",
    featured: false,
  },
  {
    id: "rt-017",
    title: "Affordable 2BHK, Attapur",
    address: "Pillar No. 145, Attapur",
    locality: "Attapur",
    city: "Hyderabad",
    pincode: "500048",
    lat: 17.3644,
    lng: 78.4218,
    price: 6800000,
    pricePerSqft: 5450,
    beds: 2,
    baths: 2,
    sqft: 1248,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Unfurnished",
    facing: "West",
    floor: 4,
    totalFloors: 7,
    yearBuilt: 2015,
    parking: 1,
    description:
      "Sensible two-bedroom on the PVNR Expressway corridor, which makes the airport a twenty-minute run and the old city fifteen. Attapur is unglamorous but well connected, and pricing reflects that.",
    amenities: ["Lift", "Power backup", "Parking", "Security", "Borewell", "Rainwater harvesting"],
    images: ["/images/listings/rt-017-1.jpg", "/images/listings/rt-017-2.jpg"],
    agent: agents.imran,
    listedDate: "2026-07-10",
    featured: false,
  },
  {
    id: "rt-018",
    title: "4BHK duplex, Kondapur",
    address: "Botanical Garden Road, Kondapur",
    locality: "Kondapur",
    city: "Hyderabad",
    pincode: "500084",
    lat: 17.4615,
    lng: 78.3639,
    price: 27800000,
    pricePerSqft: 8950,
    beds: 4,
    baths: 4,
    sqft: 3105,
    propertyType: "Apartment",
    status: "Ready to Move",
    furnishing: "Semi-furnished",
    facing: "South-East",
    floor: 9,
    totalFloors: 12,
    yearBuilt: 2020,
    parking: 2,
    description:
      "Duplex across the ninth and tenth floors with an internal staircase and double-height living volume. Opposite the Botanical Garden, so the outlook stays green and won't be built out. Five minutes to HITEC City.",
    amenities: ["Duplex layout", "Double-height living", "Swimming pool", "Gym", "Clubhouse", "Power backup", "Lift", "Gated community"],
    images: ["/images/listings/rt-018-1.jpg", "/images/listings/rt-018-2.jpg", "/images/listings/rt-018-3.jpg"],
    agent: agents.divya,
    listedDate: "2026-06-04",
    featured: false,
  },
  {
    id: "rt-019",
    title: "Farmhouse plot with mango orchard, Moinabad",
    address: "Chevella Road, Moinabad",
    locality: "Moinabad",
    city: "Hyderabad",
    pincode: "501504",
    lat: 17.2894,
    lng: 78.2087,
    price: 21000000,
    pricePerSqft: 1050,
    beds: 1,
    baths: 1,
    sqft: 20000,
    propertyType: "Plot",
    status: "For Sale",
    furnishing: "Unfurnished",
    facing: "North",
    floor: null,
    totalFloors: null,
    yearBuilt: 2019,
    parking: 4,
    description:
      "Half an acre on Chevella Road with roughly sixty mature mango trees and a single-room caretaker structure with power and a borewell already in place. Forty minutes from Gachibowli on a clear morning. Clear title, single owner since 2019.",
    amenities: ["Mango orchard", "Borewell", "Electricity connection", "Caretaker room", "Compound fencing", "Clear title"],
    images: ["/images/listings/rt-019-1.jpg", "/images/listings/rt-019-2.jpg"],
    agent: agents.rajesh,
    listedDate: "2026-05-08",
    featured: false,
  },
  {
    id: "rt-020",
    title: "3BHK new launch, Uppal metro corridor",
    address: "Ramanthapur Road, Uppal",
    locality: "Uppal",
    city: "Hyderabad",
    pincode: "500039",
    lat: 17.4058,
    lng: 78.5591,
    price: 9800000,
    pricePerSqft: 5900,
    beds: 3,
    baths: 3,
    sqft: 1660,
    propertyType: "Apartment",
    status: "New Launch",
    furnishing: "Unfurnished",
    facing: "East",
    floor: 6,
    totalFloors: 15,
    yearBuilt: 2028,
    parking: 1,
    description:
      "East Hyderabad has been the quiet story of the last two years, and this launch sits four hundred metres from Uppal metro on the Blue Line. Possession mid-2028, RERA registered, construction-linked payments.",
    amenities: ["Metro nearby", "Clubhouse", "Gym", "Children's play area", "Power backup", "Lift", "Gated community"],
    images: ["/images/listings/rt-020-1.jpg", "/images/listings/rt-020-2.jpg"],
    agent: agents.sneha,
    listedDate: "2026-07-14",
    featured: false,
  },
];

/* ---------- helpers ---------- */

/** ₹1.45Cr / ₹82L / ₹9,600 — Indian short-form currency. */
export function formatINR(rupees: number): string {
  if (rupees >= 10000000) {
    const cr = rupees / 10000000;
    return `₹${cr % 1 === 0 ? cr : cr.toFixed(2).replace(/0$/, "")}Cr`;
  }
  if (rupees >= 100000) {
    const lakh = rupees / 100000;
    return `₹${lakh % 1 === 0 ? lakh : lakh.toFixed(1)}L`;
  }
  return `₹${rupees.toLocaleString("en-IN")}`;
}

/** "₹8,100/sqft" */
export function formatPerSqft(value: number): string {
  return `₹${value.toLocaleString("en-IN")}/sqft`;
}

export const localities = [...new Set(listings.map((l) => l.locality))].sort();
export const propertyTypes = [...new Set(listings.map((l) => l.propertyType))].sort();
export const featuredListings = listings.filter((l) => l.featured);

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

/** Map bounds covering all listings — useful for Leaflet fitBounds on load. */
export const cityBounds: [[number, number], [number, number]] = [
  [17.2894, 78.1985],
  [17.5462, 78.5591],
];

export const cityCenter: [number, number] = [17.4239, 78.4083];
